// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadCollection():Promise<main.Collection>;

export function Send(arg1:string):Promise<main.Response>;
